basePath: /
host: localhost:8080
info:
  contact: {}
  description: Application for planning your journey
  title: Journer Planner
paths:
  /auth/signIn:
    post:
      consumes:
      - application/json
      description: Authorization to the account
      parameters:
      - description: your login or email
        in: query
        name: option
        required: true
        type: string
      - description: your password
        in: query
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: SignIn
      tags:
      - users
  /auth/singUp:
    post:
      consumes:
      - application/json
      description: Create account
      parameters:
      - description: your login
        in: query
        name: login
        required: true
        type: string
      - description: your password
        in: query
        name: password
        required: true
        type: string
      - description: your email
        in: query
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: SignUp
      tags:
      - users
  /groups/add:
    post:
      consumes:
      - application/json
      description: Create new group
      parameters:
      - description: name of group
        in: query
        name: name
        required: true
        type: string
      - collectionFormat: multi
        description: by adding logins you will automatically invite this users
        in: query
        items:
          type: string
        name: invites
        type: array
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: AddGroup
      tags:
      - groups
  /groups/declineinvite:
    post:
      consumes:
      - application/json
      description: Decline invite
      parameters:
      - description: Id of invite
        in: query
        name: invite_id
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: Decline invite
      tags:
      - invites
  /groups/delete:
    delete:
      consumes:
      - application/json
      description: Delete group by id
      parameters:
      - description: id of group
        in: query
        name: group_id
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: DeleteGroup
      tags:
      - groups
  /groups/getgroupinfo:
    get:
      consumes:
      - application/json
      description: Get full info about group you are a member of
      parameters:
      - description: id of group
        in: query
        name: group_id
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: GetGroupInfo
      tags:
      - groups
  /groups/getlist:
    get:
      consumes:
      - application/json
      description: Get a list of all the groups you are a member of
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: GetGroups
      tags:
      - groups
  /groups/givelead:
    put:
      consumes:
      - application/json
      description: Give another member of group leader role
      parameters:
      - description: member login
        in: query
        name: user_login
        required: true
        type: string
      - description: id of group
        in: query
        name: group_id
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: GiveLeaderRole
      tags:
      - groups
  /groups/invite:
    post:
      consumes:
      - application/json
      description: Invite user to group
      parameters:
      - description: id of group
        in: query
        name: group_id
        required: true
        type: string
      - description: invited user
        in: query
        name: user_login
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: Invite user to group
      tags:
      - invites
  /groups/invitelist:
    get:
      consumes:
      - application/json
      description: Get your list of invites
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: Get invite list
      tags:
      - invites
  /groups/leaveGroup:
    post:
      consumes:
      - application/json
      description: Leave from group
      parameters:
      - description: id of group
        in: query
        name: group_id
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: LeaveFromGroup
      tags:
      - groups
  /tasks/add:
    post:
      consumes:
      - application/json
      description: Create new task
      parameters:
      - description: Id of group
        in: query
        name: group_id
        required: true
        type: string
      - description: Task Details
        in: query
        name: title
        required: true
        type: string
      - example: "2024-10-21"
        in: query
        name: start_date
        type: string
      - example: "14:00"
        in: query
        name: start_time
        type: string
      - example: 0
        in: query
        name: days
        type: integer
      - example: 2
        in: query
        name: hours
        type: integer
      - example: 30
        in: query
        name: minutes
        type: integer
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: AddTask
      tags:
      - Tasks
  /tasks/delete:
    delete:
      consumes:
      - application/json
      description: Delete existing task
      parameters:
      - description: Id of group
        in: query
        name: group_id
        required: true
        type: string
      - description: Id of group
        in: query
        name: task_id
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: DeleteTask
      tags:
      - Tasks
  /tasks/getlist:
    get:
      consumes:
      - application/json
      description: Create new task
      parameters:
      - description: Id of group
        in: query
        name: group_id
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: GetTasks
      tags:
      - Tasks
  /tasks/update:
    put:
      consumes:
      - application/json
      description: update existing task
      parameters:
      - description: Id of group
        in: query
        name: group_id
        required: true
        type: string
      - description: task id
        in: query
        name: task_id
        required: true
        type: string
      - description: Task Details
        in: query
        name: title
        type: string
      - example: "2024-10-21"
        in: query
        name: start_date
        type: string
      - example: "14:00"
        in: query
        name: start_time
        type: string
      - example: 0
        in: query
        name: days
        type: integer
      - example: 2
        in: query
        name: hours
        type: integer
      - example: 30
        in: query
        name: minutes
        type: integer
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: UpdateTask
      tags:
      - Tasks
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
